// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrm7ZOYS2Jgkdd6rjHpIFDldr2bB4kbcc',
    appId: '1:175459918365:android:a2889e3bffbd6024ab1cf4',
    messagingSenderId: '175459918365',
    projectId: 'parrot-english-app',
    storageBucket: 'parrot-english-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiTfi6D2dLVwRdnwfIe0q12xIL2MmzLGg',
    appId: '1:175459918365:ios:1c81cd1d30957019ab1cf4',
    messagingSenderId: '175459918365',
    projectId: 'parrot-english-app',
    storageBucket: 'parrot-english-app.firebasestorage.app',
    iosBundleId: 'com.example.parrot',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ60Zo6vE1N0rCvp1_RycVNUWeoYm0K7w',
    appId: '1:175459918365:web:c681aa3c0bc05492ab1cf4',
    messagingSenderId: '175459918365',
    projectId: 'parrot-english-app',
    authDomain: 'parrot-english-app.firebaseapp.com',
    storageBucket: 'parrot-english-app.firebasestorage.app',
    measurementId: 'G-4WGN8P778C',
  );
}
